-- Created by Vertabelo (http://vertabelo.com)
-- Script type: create
-- Scope: [tables, references, sequences, views, procedures]
-- Generated at Sun Jan 04 15:37:08 UTC 2015




-- tables
-- Table: ANGAJATI
CREATE TABLE ANGAJATI (
    IDA serial  NOT NULL,
    NUME varchar(30)  NOT NULL,
    PRENUME varchar(60)  NOT NULL,
    RANG int  NOT NULL,
    SALARIU money  NOT NULL,
    PAROLA varchar(32)  NOT NULL,
    MAIL varchar(100)  NOT NULL,
    CONSTRAINT ANGAJATI_pk PRIMARY KEY (IDA)
);



-- Table: CLIENTI
CREATE TABLE CLIENTI (
    IDC serial  NOT NULL,
    ID_USER int  NOT NULL,
    MAIL varchar(100)  NOT NULL,
    PAROLA varchar(32)  NOT NULL,
    BCODE varchar(10)  NOT NULL,
    CONSTRAINT CLIENTI_pk PRIMARY KEY (IDC)
);



-- Table: CONTURI
CREATE TABLE CONTURI (
    NR_CARD varchar(16)  NOT NULL,
    NUME varchar(30)  NOT NULL,
    PRENUME varchar(60)  NOT NULL,
    CNP varchar(13)  NOT NULL,
    CI varchar(8)  NOT NULL,
    ADRESA varchar(255)  NOT NULL,
    MAIL varchar(100)  NOT NULL,
    TIP int  NOT NULL,
    DATA_CR date  NOT NULL,
    TELEFON varchar(15)  NOT NULL,
    SOLD decimal(10,3)  NOT NULL,
    BCODE varchar(10)  NOT NULL,
    NR_CONT varchar(24)  NOT NULL,
    IDC serial  NOT NULL,
    CONSTRAINT BCODE UNIQUE (BCODE) NOT DEFERRABLE  INITIALLY IMMEDIATE ,
    CONSTRAINT CONTURI_pk PRIMARY KEY (IDC)
);



-- Table: CONTURI_SPECIALE
CREATE TABLE CONTURI_SPECIALE (
    IDCS serial  NOT NULL,
    NR_CONT varchar(24)  NOT NULL,
    NUME_FIRMA varchar(50)  NOT NULL,
    ADRESA varchar(255)  NOT NULL,
    TELEFON varchar(15)  NOT NULL,
    MAIL varchar(100)  NOT NULL,
    SOLD money  NOT NULL,
    CONSTRAINT CONTURI_SPECIALE_pk PRIMARY KEY (IDCS)
);



-- Table: OPERATII
CREATE TABLE OPERATII (
    IDO serial  NOT NULL,
    NR_CONTC varchar(24)  NOT NULL,
    IDA int  NOT NULL,
    DATA date  NOT NULL,
    TIP_OP varchar(40)  NOT NULL,
    NR_CONTF varchar(24)  NULL,
    CONSTRAINT NR_CONTC UNIQUE (NR_CONTC) NOT DEFERRABLE  INITIALLY IMMEDIATE ,
    CONSTRAINT IDA UNIQUE (IDA) NOT DEFERRABLE  INITIALLY IMMEDIATE ,
    CONSTRAINT NR_CONTF UNIQUE (NR_CONTF) NOT DEFERRABLE  INITIALLY IMMEDIATE ,
    CONSTRAINT OPERATII_pk PRIMARY KEY (IDO)
);







-- foreign keys
-- Reference:  ANGAJATI_OPERATII (table: ANGAJATI)


ALTER TABLE ANGAJATI ADD CONSTRAINT ANGAJATI_OPERATII 
    FOREIGN KEY (IDA)
    REFERENCES OPERATII (IDA)
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE 
;

-- Reference:  CLIENTI_CONTURI (table: CLIENTI)


ALTER TABLE CLIENTI ADD CONSTRAINT CLIENTI_CONTURI 
    FOREIGN KEY (BCODE)
    REFERENCES CONTURI (BCODE)
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE 
;

-- Reference:  CONTURI_OPERATII (table: CONTURI)


ALTER TABLE CONTURI ADD CONSTRAINT CONTURI_OPERATII 
    FOREIGN KEY (NR_CONT)
    REFERENCES OPERATII (NR_CONTC)
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE 
;

-- Reference:  CONTURI_SPECIALE_OPERATII (table: CONTURI_SPECIALE)


ALTER TABLE CONTURI_SPECIALE ADD CONSTRAINT CONTURI_SPECIALE_OPERATII 
    FOREIGN KEY (NR_CONT)
    REFERENCES OPERATII (NR_CONTF)
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE 
;






-- End of file.

